version: '2'

services:
  todo_app:
    image: 'bitnami/symfony:1'
    ports:
      - '443:8000'
    volumes:
      - '.:/app'
    environment:
      - SYMFONY_PROJECT_NAME=todo_app
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MARIADB_USER=tduser
      - MARIADB_PASSWORD=uOrGEPhOueTE
      - MARIADB_DATABASE=todo_db
    depends_on:
      - mariadb
  mariadb:
    image: 'bitnami/mariadb:10.3'
    ports:
      - '3906:3306'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=tduser
      - MARIADB_PASSWORD=uOrGEPhOueTE
      - MARIADB_DATABASE=todo_db
      - MARIADB_ROOT_PASSWORD=zO4.G8P.6eTv
    volumes:
      - ./db_dump:/dump