version: '2'

services:
  todo_app:
    image: 'bitnami/symfony:1'
    ports:
      - '8000:8000'
    volumes:
      - '.:/app'
    environment:
      - SYMFONY_PROJECT_NAME=myapp
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MARIADB_USER=tduser
      - MARIADB_PASSWORD=uOrGEPhOueTE
      - MARIADB_DATABASE=td_db
    depends_on:
      - mariadb
  mariadb:
    image: 'bitnami/mariadb:10.3'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=tduser
      - MARIADB_PASSWORD=uOrGEPhOueTE
      - MARIADB_DATABASE=td_db